### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by tufu9441** [zdotsh/git-io-replace#1]
### Old URL

https://git.io/maup

### Destnation URL

https://github.com/tufu9441/maupassant-hexo

### Code of Conduct

- [X] I confirm that I have read the [requirements](https://github.com/zdotsh/git-io-replace#requirements) and understand the consequences.
- [X] I confirm that I know there's no SLA for this service.
- [x] I checked to make sure that this request has not already been filed.
- [X] I confirm that I am the owner of the GitHub repository that I am requesting a replacement for.

**Comment by Showfom** [comment]
https://z.sh/maup

Done
